spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
